version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/genofire/logmania
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go install github.com/genofire/logmania
      - store_artifacts:
          path: /go/bin/
          destination: logmania
  test:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/genofire/logmania
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go get github.com/mattn/goveralls
      - run: go get golang.org/x/tools/cmd/cover
      - run: ./.test-coverage circle-ci
      - store_test_results:
          path: ./
          destination: profile.cov
  test_race:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/genofire/logmania
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go test -race ./...
  deploy:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/genofire/logmania
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go install github.com/genofire/logmania
      - run: ./deploy.sh $HOST_FOR_STAGING $PORT_FOR_STAGING
workflows:
  version: 2
  build_and_tests:
    jobs:
      - build
      - test
      - test_race
      - deploy:
          requires:
            - build
            - test
            - test_race
